---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-demo-deployment
  namespace: self-hosted
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cicd-demo
  template:
    metadata:
      labels:
        app: cicd-demo
    spec:
      imagePullSecrets:
        - name: dockerhub-image-pull-secret
      containers:
        - name: cicd-demo
          image: hongsait/cpsy-350-ci-python:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: cicd-demo-service
  namespace: self-hosted
spec:
  selector:
    app: cicd-demo
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
